sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/chrome-vnc
  - secure: irlThMEQmEcoSOe7Rf56ist6Cn2Q/E6Ax7hCaU7QO2mj1HfljktCdDr+jqY/wcJJpjGvziFKn9nMOsYLt5NIacvpcLkdfROilHl9/sg2GIz5L68r1hfyRuJeecuSSwgyLqA+fOBTuluXLTMORTZcgRscJQ9X/7yvbnnnh+5tuCDZ7Oyjb7avH3FnV17KmzinZoQv6pJ5xV/qvARK2+GKUzOZ/QGv1Q47nLMnehpBhZh7pUkObkG64rBtPSvUXgalmOYZWBUbt+WveviRyDBZ4kNBkPoLHP/AFOtPh5yNPI9E4Jg7c68BP8gir0ICxB0c5UyaeL2eU9b5FQwR89zV5NT3bVomfQo2NDwDDMT+amL+h9SITRN/Vmn7VLVIACtJ+CfHXgitRxZo40bKLVZuP2P8uflpREc5naFWYM+h/csYvIUrdpDtid8Xm8Rw0Ni+HiWDpu+8mINbyUymeXqj1pFvaYfNTYqZgYd4ewAK1aRYcdp9xcMKVjgw+Ej5UNNaRwQOtNx2utrHGOq4F3Wm9qCzDB/eHdjvgPoTYBUMkq0JsEXA6a2T2tmWn8IeDv6+9MVZv7WWK4EGDT97mfvC6hlQCUY1kLQbzACXxWSPSgNoWT5HuetvGX5WJ3V7nvWW7aYuydahke5JNjCG7OPiSae0cRYFwm/eC9KJQhgt32k=
  - secure: hdRDUtzfDqysMmHl0ri+diUKe4abQe/a+pxrN/RD8AFyqYbtkNUASDc3V91peJSSrKTFlk+znRak5b+WJT7rZlX6aCc+0z9tGYAmPYSfP+ej6g230xxSsN1GktZ9P8WUDtvpd2X1GRvLOGFxW/rlIJIAiDnI7kCSKpZLzoAF3KXmuneyQ8nm497eUZ5NP8iCydgIzV53wqljWSTcV8c5dX3PM9Ca3OU1imjpHrmXPZcZU20Xj0Rw46kcbjboPQpcR3QPnUIRjC4c90dJAOM6TK/GXDkHHeNvF5PDSQE4GwoCmu0l/1Ebs4JG3BpSfeytGMUlyQlypcq2JKvbLmsaHDmu6fU0b90GD8ir/5F16zWtatsPPcZh+FwvZSpK53qciOs3V6i/0X5bDHSYeuWsZRPEPstrRGSW1+UMCQ7Nv7v1XNZptFsfRZThXnYjNNS+OAMjWTkCiNXinaGv9cT52nJz/ZsDZcUfFt9CmoOhuzFJxk+0lGAqRcQcs6PsU7ZpnXUwqjBAlbtRbrI5ZIas3rMGV9QNy7t4fWwX1NpouIUz/syDsje7ZmRDQz2udUPmCH0bX9d0a0q7yIbpzCAxGQvLamd58gWEPJQE6x/rrOQBCfkIpL4yoFwqAoxrm9++8Fq8X1AhcA19x8zNZxJu90sJu3yz5Zl+gn/eNsvF438=
before_script:
- cd base-chrome
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile.vnc.chrome" .
after_script:
- version="$(awk -F '[=.]'  '/ARG CHROME_DRIVER_VERSION/ {print $2}' Dockerfile.vnc.chrome)"
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:chrome${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:chrome${version}"
  on:
    branch: master