sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/chrome-vnc
  - secure: T8N3U/A3XIhW9VVqGOhpUROPuCjMjVNs2tmNNCD2CHgGcSgCrktsbk/nbX1IqIvZfBegs5pvL57/o3FoBFrnQzb3t7k3IRALrRT8QrqzqRJ9/M6Og0MZE7v+dSID2YA+lNCuMsp5rAfcUu9aup42wMOMTm5LXawNaK+iFQP17mxHogAz8DwQbXWtp7MM3U0mMwTJhIzzXbDCORfwZD7C0iQWlRWdw5Xd6Ci3v9kQFTQ8RPdXsHP4sJ5Xs9rZ7qTGw4WOtELAUI1pYPpO38cvwz2JprDA3YQxHSRhlDvPGI9/cgZAEqdjkaFT9lUhk/PyEEf+ZTHRb9xIY60FlVBllPYyhLt5/yTvzjzib/qualPV5Nh+fcKlM6fVJHXm8jTHEttQ6b1jrP05hJXWZaS4U0e2Gkd/MdgOQ6zDHHIxIGxoG94yIvSGCO4v/Ye5aGe0ovKLcU2M7OjZvJjsPZb9Uhw/Gq079SiRME4CyPtEc7MusRZVEIVKb9dQJkpv9AIN+ddHqDAycePetdtCsPgpG3ax7e6v6+hATguVQ3ClVZTjIhvol9Pd0Jj4gKKgpYFhwqBRzAmwLoCKRkltMeUwMLUh45VCPn0IG8lBWsMLRGlITUEip2iM9bnJngGYEGiElB+KGGvPqsudUCtZ5EW7cEWMxopqR1t0geAoIikXRt8=
  - secure: YVC60A1YoGaZ7TP+XQV93bSluHxqw2VDgpAUGFbL+UQOAO/8gZ2yuAb68XwS4WqyS46UjaVGUdCAA8SO8+K4o0kv3jTjiW0cHvHCsiHLRm4EO1wecXEfqilK3tP0nbUyzzIrmrJhvddZFvlNlAOxrOjfk+bgHKu/E4mGHzLvMrBmqDoLabfV101y+1IIzmAcSEx7f6SlJLON2eHoke/UnJAsb1LgAPCTfSs9dr8VW6hKzxkhoLrv8/1Wtl5X0GvGoDTnnUrXkFBm+ZfbS2H5ykVShLHcdC3VWmUJjw5t4o+xHTvBVIk7aDjErQYqdpxWTCvdOUWAg+r4UhE+t5UM+nvY11K7DfkoUngck7we7obAy5pevLY61qhb0ldZan9vOmA5Nd0SsQZMsvhuxXlCOVrgSmD41AnhOywMCrSLs1cfNpN9Tbd6c7IGckcLQ+80ySdKua5dpyPiUx4yXmS7HRqm/1XzMIrA6Q649OAUiQjuq9/2D95I/0uQ+A9s/qJWHru1JUlVWBfAXg244xn0GhKzf1oa+fkGNVOIb+I0w7uTzJzr3JeRfmMbOJJ6LsJJhGJ3E3eEMEuMQaqAeooK/+goW2r34OLXW/arBTcih6xULfhJ/Cq32c2lnBT+XKyZ+BMyaqrwsfbORpl/Nclzoytz3oSVJ6E1XGNkiLvVeDc=
before_script:
- cd base-chrome
- version="$(awk -F '[=.]'  '/ARG CHROME_VERSION/ {print $2}' Dockerfile.vnc.chrome)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile.vnc.chrome" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:chrome${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:chrome${version}"
  on:
    branch: master
