name: Build and Push Image

on:
  push:
    branches:
      - chrome83
    paths:
      # '*' matches any character except '/'
      - 'base-chrome/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: chrome83      
      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
          DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin
      - name: Build & Push Image
        run: |
          cd base-chrome
          IMAGE_NAME=ringcentral/chrome-vnc
          IMAGE_TAG=chrome83
          VERSION="chrome$(awk -F '[=.]'  '/ARG CHROME_VERSION/ {print $2}' Dockerfile.vnc.chrome)"
          docker build -t ${IMAGE_NAME} -f Dockerfile.vnc.chrome .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_TAG}"

          docker push "${IMAGE_NAME}:${VERSION}"
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"