name: Build Image

on:
  pull_request:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Image
        run: |
          cd base-chrome
          IMAGE_NAME=ringcentral/chrome-vnc
          Chrome_VERSION="chrome$(awk -F '[=.]'  '/ARG CHROME_VERSION/ {print $2}' Dockerfile.vnc.chrome)"
          Firefox_VERSION="firefox$(awk -F '[=.]'  '/ARG FIREFOX_VERSION/ {print $2}' Dockerfile.vnc.chrome)"
          docker build -t ${IMAGE_NAME} -f Dockerfile.vnc.chrome .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${Chrome_VERSION}_${Firefox_VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"